### ISSUE TITLE
Incorrect result in BigInt.xor()

### ISSUE THREAD

**Issue by safris** [bwakell/Huldra#17]
The following test suggests there's a problem with the xor algorithm:

**The following fails:**

```java
final BigInteger facit = BigInteger.valueOf(-1).xor(BigInteger.valueOf(Long.MAX_VALUE));
final BigInt a = new BigInt(-1);
a.xor(new BigInt(Long.MAX_VALUE));
assertEquals(facit.toString(), a.toString());
```

I'm trying to understand the algorithm in order to find why there is a problem with `Long.MAX_VALUE`, but there is no problem with `Integer.MAX_VALUE`.

**The following passes:**

```java
final BigInteger facit = BigInteger.valueOf(-1).xor(BigInteger.valueOf(Integer.MAX_VALUE));
final BigInt a = new BigInt(-1);
a.xor(new BigInt(Integer.MAX_VALUE));
assertEquals(facit.toString(), a.toString());
```

**Comment by safris** [comment]
I've extended this test to show a bigger range of results that follow a similar pattern of inputs:

```java
@Test
public void test() {
  test(0);
  for (int i = 1; i < 3; ++i) {
    test(i);
    test(-i);
  }
}

public void test(final int offset) {
  for (int i = 1; i < 64; ++i) {
    final BigInteger a1 = BigInteger.TWO.pow(i * 8 - 1 + offset).subtract(BigInteger.ONE);
    final BigInt b1 = new BigInt(a1.toString());
    assertEquals(a1.toString(), b1.toString());

    BigInteger a2 = BigInteger.valueOf(-1);
    final BigInt b2 = new BigInt(-1);
    assertEquals(a2.toString(), b2.toString());

    a2 = a2.xor(a1);
    b2.xor(b1);

    System.out.println("-1 ^ (2^(" + i + " - 1 + " + offset + ") - 1): " + (a2.toString().equals(b2.toString()) ? "PASS" : "FAIL"));
  }
}
```

This test does not exactly help isolate the specific part of the algorithm that is in error, but it does suggest there may indeed be a problem.

Unless, are my expectations for the results of `BigInteger` to equal those of `BigInt` incorrect here in some way?

**Comment by bwakell** [comment]
Nice find.

I suspect this happens when the left side operand A is negative and the right side operand B is positive and also requires more limbs (blocks of 32 bits) than A. Then when doing A ^= B, it seems like the code is simply just copying over the higher order limbs/bits from B to A (after having allocated more space for A). That is incorrect as for negative numbers, one should imagine them in two complement form, i.e. that they have leading ones extending into infinity, so when the higher order limbs are copied over they should be inverted (as that is what xor'ing with a 1 does).

However, I only had a quick look (and sadly not enough time to dig deeper) so I might be mistaken, but it might be worth testing if A ^= B fails for any input where A = -1 (or negative and requires less than 32 bits) and B > 2^32.

**Comment by safris** [comment]
Hi @bwakell, you are correct, the test in my second comment suggests that A ^= B fails for:

>  any input where A = -1 (or negative and requires less than 32 bits) and B > 2^32.

as its output shows `PASS` for B = {7F, 7FFF, 7FFFFF, 7FFFFFFF}, and `FAIL` for values that are bigger than 2^32.

It also appears that if I reverse A and B, then the xor algorithm works as expected.

**Comment by bwakell** [comment]
Well when you have the reversed scenario then the size of the first operand is bigger than the second operand, so the aspect (bug) of blindly copying over the higher order limbs doesn't apply. Also you then have the scenario of `positive xor negative` (as opposed to `negative xor positive`) and the code is different for all 4 combinations of xor'ing. ^^

I suspect that there's also a bug for the case `negative xor negative`, in particular when B requires more limbs than A. Have you tried if `A = -1` xor `B = -2^42` (or where B is negative and has a magnitude larger than `2^32`) fails as well?

**Comment by bwakell** [comment]
Actually, I had a closer look now and it's not about the higher order limbs, they seem to work quite alright (there might be a bug there, but not in this case necessarily). The bug is actually way more profound. :)

It's easiest exposed by the following simple test case: `-1 xor 2^32-1`
The right answer is `-4294967296` but the code returns `0`.

The bug is in the following line: `dig[j-1] = -(-a^b);`
Where `a` and `b` are the first non-zero limbs of the respective numbers.
Since the first number is negative, we convert `a` to its two complement form, so what is internally stored as `1` becomes `-1` (in other words a bit representation of all ones). The second number is already positive so it remains how it is, i.e. `2^32-1` (in other words a bit representation of all ones). The xor of these two limbs is obviously `0`, so far so good.

OK so the answer for this limb in two complement form is `0`, but we now want to convert it back into normalized form. This is easily achieved by inverting all bits and adding one, i.e. `~x + 1`, this is equivalent to `-x`... except for the case where `x=0` because then we get a carry to the next limb, and that's exactly the case we have here and we're forgetting to do the carry.

So the bug happens because "who would've thought that the xor of two numbers requiring 32 bits of storage could yield a result requiring 64 bits of storage". ^^
Once again, really nice find. I'll try to get this fixed over the next week (when I have time). Though I fear that similar assumptions are made in other places for the bit-operations... but oh well we'll hunt them down one by one.

**Comment by safris** [comment]
Wow, thank you for the explanation. I've run that code through the debugger enough times to realize that I've seen this happen exactly as you say, but it didn't occur to me that there is a carry getting lost. Thank you for looking into this.

**Comment by bwakell** [comment]
OK so just below said line, adding the following should fix the issue:
```
					if(dig[j-1]==0) { // Perform carry.
						for(; dig[j-1]==0 && j<mlen; j++) {
							dig[j] ^= mask.dig[j]; ++dig[j];
						}
						final int blen = Math.max(len, mask.len);
						for(; dig[j-1]==0 && j<blen; j++) ++dig[j];
						if(j==dig.length) realloc(j+1);
						if(dig[j-1]==0){ dig[j] = 1; len=j+1; return; }
					}
```

Now I just need to add the right unit tests...

**Comment by bwakell** [comment]
Hopefully I have now fixed this. Feel free to reopen if you find any other edge case that I missed. ^^

**Comment by safris** [comment]
My tests are passing with you fix. Thank you @bwakell!
