### ISSUE TITLE
Bug within divRem()

### ISSUE THREAD

**Issue by lujunbofan** [bwakell/Huldra#2]
There is likely to be a bug within the divrem() method. For example:

BigInt p = new BigInt(104608886616216589L), q = new BigInt(104608886616125069L);
System.out.println(p.divRem(q).toString());

The printed result says 104608886616216589, which is the value of p, instead of 91520, which is the right answer.

**Comment by bwakell** [comment]
Long time no fix. ^^
So the issue turned out to be in the unsigned long division code. More specifically when the higher 32 bits were equal.
I added some tests as well.

(I also noticed that Java 8 provides a Long.divideUnsigned() method, which would be neat to use. However, it seems like it internally just converts the longs to BigIntegers and makes the division, which is kind of inefficient and yeah....)
